"""
Hospital HRM Framework - Version 4
==================================

V4 adds the first trainable RL layer on top of the validated V3 environment.

Pipeline
--------
V2 skill-aware CP-SAT baseline
    -> V3 dynamic staff-level environment
    -> V4 PPO policy
    -> controlled evaluation against no-op baseline

Design choices
--------------
* The V3 environment remains the source of truth for operational validity.
* The PPO action space is a fixed candidate-index space of size
  ``max_candidates + 1``. Index 0 is no-op; remaining indices refer to the
  valid staff-level moves generated by V3 for the current state.
* Invalid/padded candidate indices are masked before action selection.
* The policy never directly edits the roster. It selects an action and V3
  validates/applies it.
* Training uses controlled stochastic events generated by V3.
* Evaluation uses paired scenarios: PPO and a no-op policy see the same
  initial baseline and the same forced events.

This remains a research/decision-support prototype, not a clinical production
system.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions import Categorical

from hospital_hrm_framework_v3 import (
    DynamicHospitalWorkforceEnvironment,
    V3EnvironmentConfig,
    load_v2_baseline,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("hospital_hrm_v4")


@dataclass
class V4PPOConfig:
    seed: int = 42
    episodes: int = 150
    learning_rate: float = 3e-4
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_epsilon: float = 0.20
    value_coef: float = 0.50
    entropy_coef: float = 0.01
    max_grad_norm: float = 0.50
    update_epochs: int = 4
    minibatch_size: int = 128
    hidden_size: int = 128
    episode_days: int = 7
    max_candidates: int = 64
    time_limit: int = 120
    output_dir: str = "v4_outputs"


class ActorCritic(nn.Module):
    def __init__(self, state_dim: int, action_dim: int, hidden_size: int = 128):
        super().__init__()
        self.shared = nn.Sequential(
            nn.Linear(state_dim, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
        )
        self.policy_head = nn.Linear(hidden_size, action_dim)
        self.value_head = nn.Linear(hidden_size, 1)

    def forward(self, x: torch.Tensor):
        h = self.shared(x)
        return self.policy_head(h), self.value_head(h).squeeze(-1)


class PPOAgent:
    def __init__(self, state_dim: int, action_dim: int, config: V4PPOConfig):
        self.config = config
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = ActorCritic(state_dim, action_dim, config.hidden_size).to(self.device)
        self.optimizer = optim.Adam(self.model.parameters(), lr=config.learning_rate)

    def _masked_dist(self, logits: torch.Tensor, mask: torch.Tensor):
        masked = logits.masked_fill(~mask, torch.finfo(logits.dtype).min)
        return Categorical(logits=masked)

    @torch.no_grad()
    def act(self, state: np.ndarray, valid_count: int, deterministic: bool = False):
        x = torch.as_tensor(state, dtype=torch.float32, device=self.device).unsqueeze(0)
        logits, value = self.model(x)
        mask = torch.zeros_like(logits, dtype=torch.bool)
        mask[:, :max(1, min(valid_count, logits.shape[1]))] = True
        dist = self._masked_dist(logits, mask)
        action = torch.argmax(dist.probs, dim=-1) if deterministic else dist.sample()
        log_prob = dist.log_prob(action)
        return int(action.item()), float(log_prob.item()), float(value.item())

    def evaluate_actions(self, states, actions, masks):
        # Protect the neural network from invalid input values.
        states = torch.nan_to_num(
            states,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        logits, values = self.model(states)

        # Protect against numerical instability in the network.
        logits = torch.nan_to_num(
            logits,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        values = torch.nan_to_num(
            values,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        # Ensure every state has at least one valid action.
        masks = masks.clone()

        no_valid_actions = ~masks.any(dim=1)
        if no_valid_actions.any():
            masks[no_valid_actions, 0] = True

        masked = logits.masked_fill(
            ~masks,
            torch.finfo(logits.dtype).min
        )

        dist = Categorical(logits=masked)

        return (
            dist.log_prob(actions),
            dist.entropy(),
            values,
        )

    def update(self, batch: Dict[str, np.ndarray]):
        device = self.device

        states = torch.as_tensor(
            batch["states"],
            dtype=torch.float32,
            device=device,
        )

        actions = torch.as_tensor(
            batch["actions"],
            dtype=torch.long,
            device=device,
        )

        old_log_probs = torch.as_tensor(
            batch["log_probs"],
            dtype=torch.float32,
            device=device,
        )

        returns = torch.as_tensor(
            batch["returns"],
            dtype=torch.float32,
            device=device,
        )

        advantages = torch.as_tensor(
            batch["advantages"],
            dtype=torch.float32,
            device=device,
        )

        masks = torch.as_tensor(
            batch["masks"],
            dtype=torch.bool,
            device=device,
        )

        # ---------------------------------------------------------
        # Numerical safety
        # ---------------------------------------------------------

        states = torch.nan_to_num(
            states,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        old_log_probs = torch.nan_to_num(
            old_log_probs,
            nan=0.0,
            posinf=0.0,
            neginf=0.0,
        )

        returns = torch.nan_to_num(
            returns,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        advantages = torch.nan_to_num(
            advantages,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        # ---------------------------------------------------------
        # Advantage normalization
        # ---------------------------------------------------------

        if advantages.numel() > 1:
            advantages = (
                                 advantages - advantages.mean()
                         ) / (
                                 advantages.std(unbiased=False) + 1e-8
                         )
        else:
            advantages = torch.zeros_like(advantages)

        # Final protection.
        advantages = torch.nan_to_num(
            advantages,
            nan=0.0,
            posinf=10.0,
            neginf=-10.0,
        )

        n = len(states)

        if n == 0:
            return 0.0

        indices = np.arange(n)
        losses = []

        for _ in range(self.config.update_epochs):

            np.random.shuffle(indices)

            for start in range(0, n, self.config.minibatch_size):

                idx = indices[start:start + self.config.minibatch_size]

                if len(idx) == 0:
                    continue

                mb = torch.as_tensor(
                    idx,
                    dtype=torch.long,
                    device=device,
                )

                new_lp, entropy, values = self.evaluate_actions(
                    states[mb],
                    actions[mb],
                    masks[mb],
                )

                new_lp = torch.nan_to_num(
                    new_lp,
                    nan=0.0,
                    posinf=0.0,
                    neginf=0.0,
                )

                entropy = torch.nan_to_num(
                    entropy,
                    nan=0.0,
                    posinf=0.0,
                    neginf=0.0,
                )

                values = torch.nan_to_num(
                    values,
                    nan=0.0,
                    posinf=1e6,
                    neginf=-1e6,
                )

                ratio = torch.exp(
                    torch.clamp(
                        new_lp - old_log_probs[mb],
                        -20.0,
                        20.0,
                    )
                )

                surr1 = ratio * advantages[mb]

                surr2 = (
                        torch.clamp(
                            ratio,
                            1.0 - self.config.clip_epsilon,
                            1.0 + self.config.clip_epsilon,
                        )
                        * advantages[mb]
                )

                policy_loss = -torch.min(
                    surr1,
                    surr2,
                ).mean()

                value_loss = nn.functional.mse_loss(
                    values,
                    returns[mb],
                )

                entropy_bonus = entropy.mean()

                loss = (
                        policy_loss
                        + self.config.value_coef * value_loss
                        - self.config.entropy_coef * entropy_bonus
                )

                # -------------------------------------------------
                # Skip invalid loss rather than corrupting model
                # -------------------------------------------------

                if not torch.isfinite(loss):
                    logger.warning(
                        "Skipping non-finite PPO loss at minibatch."
                    )
                    continue

                self.optimizer.zero_grad()

                loss.backward()

                # Protect gradients.
                nn.utils.clip_grad_norm_(
                    self.model.parameters(),
                    self.config.max_grad_norm,
                )

                # Check gradients before optimizer step.
                gradients_valid = True

                for parameter in self.model.parameters():
                    if parameter.grad is not None:
                        if not torch.isfinite(parameter.grad).all():
                            gradients_valid = False
                            break

                if not gradients_valid:
                    logger.warning(
                        "Skipping optimizer step because gradients "
                        "contain NaN or Inf."
                    )
                    self.optimizer.zero_grad()
                    continue

                self.optimizer.step()

                # Final model-parameter safety check.
                parameters_valid = True

                for parameter in self.model.parameters():
                    if not torch.isfinite(parameter).all():
                        parameters_valid = False
                        break

                if not parameters_valid:
                    logger.warning(
                        "Model parameters became non-finite after "
                        "optimizer step."
                    )

                    # Reset invalid parameters to zero.
                    for parameter in self.model.parameters():
                        parameter.data = torch.nan_to_num(
                            parameter.data,
                            nan=0.0,
                            posinf=1.0,
                            neginf=-1.0,
                        )

                losses.append(float(loss.item()))

        return float(np.mean(losses)) if losses else 0.0

    def save(self, path: str):
        torch.save({"model": self.model.state_dict(), "config": asdict(self.config)}, path)


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_env(data, roster, config: V4PPOConfig, seed: int):
    return DynamicHospitalWorkforceEnvironment(
        data,
        roster,
        V3EnvironmentConfig(
            seed=seed,
            episode_days=config.episode_days,
            max_candidates=config.max_candidates,
        ),
    )


def collect_episode(env, agent: PPOAgent, start_date: Optional[str] = None):
    state = env.reset(start_date=start_date)
    states, actions, log_probs, values, rewards, dones, masks = [], [], [], [], [], [], []
    total_reward = 0.0
    steps = 0
    while not env.done:
        valid_count = min(len(env.candidates), agent.model.policy_head.out_features)
        action, lp, value = agent.act(state, valid_count, deterministic=False)
        action_mask = np.zeros(agent.model.policy_head.out_features, dtype=bool)
        action_mask[:valid_count] = True
        next_state, reward, done, _ = env.step(action)

        # Numerical safety for environment outputs.
        state = np.nan_to_num(
            state,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        next_state = np.nan_to_num(
            next_state,
            nan=0.0,
            posinf=1e6,
            neginf=-1e6,
        )

        reward = float(
            np.nan_to_num(
                reward,
                nan=0.0,
                posinf=1e6,
                neginf=-1e6,
            )
        )

        states.append(state)
        actions.append(action)
        log_probs.append(lp)
        values.append(value)
        rewards.append(float(reward))
        dones.append(bool(done))
        masks.append(action_mask)
        total_reward += reward
        steps += 1
        state = next_state

    # Bootstrap with zero because the episode ends after the final transition.
    advantages = np.zeros(steps, dtype=np.float32)
    returns = np.zeros(steps, dtype=np.float32)
    gae = 0.0
    next_value = 0.0
    for t in reversed(range(steps)):
        nonterminal = 0.0 if dones[t] else 1.0
        delta = rewards[t] + env.config.seed * 0.0 + 0.0 * next_value - values[t]
        # For an episodic terminal rollout, next_value is zero at the end.
        if t < steps - 1:
            delta = rewards[t] + agent.config.gamma * values[t + 1] - values[t]
        gae = delta + agent.config.gamma * agent.config.gae_lambda * nonterminal * gae
        advantages[t] = gae
        returns[t] = advantages[t] + values[t]

    batch = {
        "states": np.asarray(states, dtype=np.float32),
        "actions": np.asarray(actions, dtype=np.int64),
        "log_probs": np.asarray(log_probs, dtype=np.float32),
        "returns": returns,
        "advantages": advantages,
        "masks": np.asarray(masks, dtype=bool),
    }
    return batch, total_reward, steps


def train_agent(data, roster, config: V4PPOConfig):
    set_seed(config.seed)
    probe_env = make_env(data, roster, config, config.seed)
    probe_state = probe_env.reset()
    state_dim = int(len(probe_state))
    action_dim = int(config.max_candidates + 1)
    agent = PPOAgent(state_dim, action_dim, config)

    history = []
    for episode in range(1, config.episodes + 1):
        # Cycle through different valid demand dates so the policy does not
        # learn only one fixed week.
        demand_dates = sorted(pd.to_datetime(data["demand_shift"]["date"].unique()))
        start = demand_dates[(episode - 1) % max(1, len(demand_dates))]
        batch, episode_reward, steps = collect_episode(
            make_env(data, roster, config, config.seed + episode),
            agent,
            start_date=str(pd.Timestamp(start).date()),
        )
        loss = agent.update(batch)
        history.append({
            "episode": episode,
            "reward": float(episode_reward),
            "steps": int(steps),
            "loss": float(loss),
            "mean_advantage": float(batch["advantages"].mean()),
        })
        if episode == 1 or episode % 10 == 0:
            logger.info(
                "V4 PPO episode %d/%d | reward=%.3f | loss=%.5f",
                episode, config.episodes, episode_reward, loss,
            )

    return agent, history, state_dim, action_dim


def build_forced_scenario(data, start_date: pd.Timestamp):
    demand = data["demand_shift"].copy()
    demand["date"] = pd.to_datetime(demand["date"])
    rows = demand[demand["date"] == pd.Timestamp(start_date)]
    if rows.empty:
        raise ValueError(f"No demand rows for {start_date.date()}")
    target = rows.sort_values("required_staff", ascending=False).iloc[0]
    return {
        "date": str(pd.Timestamp(start_date).date()),
        "demand_surge": [{
            "unit": str(target["unit"]),
            "shift": str(target["shift"]),
            "extra_staff": 2,
        }],
    }, str(target["unit"]), str(target["shift"])


def evaluate_policy(data, roster, agent: PPOAgent, config: V4PPOConfig, episodes: int = 20):
    dates = sorted(pd.to_datetime(data["demand_shift"]["date"].unique()))
    records = []
    transitions = []
    for i in range(episodes):
        start = pd.Timestamp(dates[i % len(dates)])
        env = make_env(data, roster, config, config.seed + 10000 + i)
        forced, target_unit, target_shift = build_forced_scenario(data, start)

        # Select two baseline-assigned staff to make the absence scenario
        # reproducible while preserving the same event for both policies.
        day_staff = roster[pd.to_datetime(roster["date"]) == start]["staff_id"].astype(str).unique().tolist()
        forced["absent_staff"] = day_staff[: min(2, len(day_staff))]
        forced_events = [forced]

        ppo_state = env.reset(start_date=str(start.date()), forced_events=forced_events)
        initial_metrics = env._all_metrics()
        ppo_total = 0.0
        ppo_actions = []
        while not env.done:
            valid_count = min(len(env.candidates), agent.model.policy_head.out_features)
            action, _, _ = agent.act(ppo_state, valid_count, deterministic=True)
            ppo_state, reward, done, info = env.step(action)
            ppo_total += reward
            ppo_actions.append(info["action"])

        ppo_final = env._all_metrics()

        # Paired no-op baseline: same forced events, no adaptation.
        base_env = make_env(data, roster, config, config.seed + 10000 + i)
        base_state = base_env.reset(start_date=str(start.date()), forced_events=forced_events)
        base_initial = base_env._all_metrics()
        base_total = 0.0
        while not base_env.done:
            base_state, reward, done, info = base_env.step(0)
            base_total += reward
        base_final = base_env._all_metrics()

        records.append({
            "episode": i + 1,
            "start_date": str(start.date()),
            "target_unit": target_unit,
            "target_shift": target_shift,
            "initial_coverage": initial_metrics["coverage"],
            "ppo_final_coverage": ppo_final["coverage"],
            "baseline_final_coverage": base_final["coverage"],
            "ppo_final_shortage": ppo_final["shortage"],
            "baseline_final_shortage": base_final["shortage"],
            "ppo_final_skill_shortage": ppo_final["skill_shortage"],
            "baseline_final_skill_shortage": base_final["skill_shortage"],
            "ppo_workload_gini": ppo_final["workload_gini"],
            "baseline_workload_gini": base_final["workload_gini"],
            "ppo_total_reward": ppo_total,
            "baseline_total_reward": base_total,
            "ppo_reassignments": sum(a.get("type") == "reassign" for a in ppo_actions),
        })
        transitions.append({
            "episode": i + 1,
            "start_date": str(start.date()),
            "forced_event": forced,
            "ppo_actions": ppo_actions,
        })
    return records, transitions


def run_v4(
    dataset_path: str,
    roster_path: Optional[str] = None,
    output_dir: str = "v4_outputs",
    episodes: int = 150,
    eval_episodes: int = 20,
    time_limit: int = 120,
):
    os.makedirs(output_dir, exist_ok=True)
    config = V4PPOConfig(episodes=episodes, output_dir=output_dir, time_limit=time_limit)
    data, roster = load_v2_baseline(dataset_path, roster_path, time_limit)

    agent, history, state_dim, action_dim = train_agent(data, roster, config)
    model_path = os.path.join(output_dir, "v4_ppo_model.pt")
    agent.save(model_path)

    history_path = os.path.join(output_dir, "v4_training_history.json")
    with open(history_path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2)

    evaluation, transitions = evaluate_policy(data, roster, agent, config, eval_episodes)
    eval_path = os.path.join(output_dir, "v4_evaluation.csv")
    pd.DataFrame(evaluation).to_csv(eval_path, index=False)

    transitions_path = os.path.join(output_dir, "v4_evaluation_transitions.json")
    with open(transitions_path, "w", encoding="utf-8") as f:
        json.dump(transitions, f, indent=2)

    df = pd.DataFrame(evaluation)
    summary = {
        "version": "4",
        "description": "PPO training and paired dynamic evaluation on the V3 environment",
        "state_dim": state_dim,
        "action_dim": action_dim,
        "training_episodes": episodes,
        "evaluation_episodes": eval_episodes,
        "device": str(agent.device),
        "mean_ppo_coverage": float(df["ppo_final_coverage"].mean()),
        "mean_noop_coverage": float(df["baseline_final_coverage"].mean()),
        "mean_ppo_shortage": float(df["ppo_final_shortage"].mean()),
        "mean_noop_shortage": float(df["baseline_final_shortage"].mean()),
        "mean_ppo_skill_shortage": float(df["ppo_final_skill_shortage"].mean()),
        "mean_noop_skill_shortage": float(df["baseline_final_skill_shortage"].mean()),
        "mean_ppo_workload_gini": float(df["ppo_workload_gini"].mean()),
        "mean_noop_workload_gini": float(df["baseline_workload_gini"].mean()),
        "mean_ppo_reassignments": float(df["ppo_reassignments"].mean()),
    }
    summary_path = os.path.join(output_dir, "v4_evaluation_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    logger.info("V4 completed. Summary: %s", summary)
    return {
        "model": model_path,
        "training_history": history_path,
        "evaluation": eval_path,
        "evaluation_transitions": transitions_path,
        "evaluation_summary": summary_path,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train/evaluate Version 4 PPO hospital workforce agent.")
    parser.add_argument("--dataset", required=True, help="Path to hospital_hrm_dataset.xlsx")
    parser.add_argument("--roster", default=None, help="Optional V2 baseline roster CSV")
    parser.add_argument("--output", default="v4_outputs")
    parser.add_argument("--episodes", type=int, default=150)
    parser.add_argument("--eval-episodes", type=int, default=20)
    parser.add_argument("--time-limit", type=int, default=120)
    args = parser.parse_args()

    outputs = run_v4(
        dataset_path=args.dataset,
        roster_path=args.roster,
        output_dir=args.output,
        episodes=args.episodes,
        eval_episodes=args.eval_episodes,
        time_limit=args.time_limit,
    )
    print("\nVersion 4 outputs:")
    for key, path in outputs.items():
        print(f"- {key}: {path}")
