"""
Hospital HRM Framework - Version 4
==================================

V4 adds the first trainable RL layer on top of the validated V3 environment.

Pipeline
--------
V2 skill-aware CP-SAT baseline
    -> V3 dynamic staff-level environment
    -> V4 PPO policy
    -> controlled evaluation against no-op baseline

Design choices
--------------
* The V3 environment remains the source of truth for operational validity.
* The PPO action space is a fixed candidate-index space of size
  ``max_candidates + 1``. Index 0 is no-op; remaining indices refer to the
  valid staff-level moves generated by V3 for the current state.
* Invalid/padded candidate indices are masked before action selection.
* The policy never directly edits the roster. It selects an action and V3
  validates/applies it.
* Training uses controlled stochastic events generated by V3.
* Evaluation uses paired scenarios: PPO and a no-op policy see the same
  initial baseline and the same forced events.

This remains a research/decision-support prototype, not a clinical production
system.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions import Categorical

from hospital_hrm_framework_v3 import (
    DynamicHospitalWorkforceEnvironment,
    V3EnvironmentConfig,
    load_v2_baseline,
    normalize_date,
    normalize_shift,
    safe_divide,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("hospital_hrm_v4")


@dataclass
class V4PPOConfig:
    seed: int = 42
    episodes: int = 150
    learning_rate: float = 3e-4
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_epsilon: float = 0.20
    value_coef: float = 0.50
    entropy_coef: float = 0.01
    max_grad_norm: float = 0.50
    update_epochs: int = 4
    minibatch_size: int = 128
    hidden_size: int = 128
    episode_days: int = 7
    max_candidates: int = 64
    time_limit: int = 120
    output_dir: str = "v4_outputs"


class EventAwareHospitalWorkforceEnvironment(DynamicHospitalWorkforceEnvironment):
    """V4.1 environment with event-local reward shaping.

    The V3 environment remains the operational source of truth. V4.1 only
    changes the learning signal so PPO receives explicit feedback for fixing
    the unit/shift affected by an absence or demand surge.
    """

    def _event_focus_metrics(self):
        """Return shortage/skill-shortage metrics for affected groups.

        For a demand surge, only the surged unit/shift is scored. For an
        absence-only event, the current-day hospital shortage is used because
        the absent staff member's source unit may already have been removed
        from the roster.
        """
        surge = list(self.last_event.get("demand_surge", [])) if self.last_event else []
        if surge:
            shortage = 0.0
            skill_shortage = 0.0
            coverage = 0.0
            groups = 0
            for item in surge:
                unit = str(item.get("unit", ""))
                shift = normalize_shift(str(item.get("shift", "Day")))
                m = self._group_metrics(pd.Timestamp(self.current_date), unit, shift)
                shortage += float(m["shortage"])
                skill_shortage += float(m["skill_shortage"])
                coverage += float(safe_divide(m["assigned"], m["required"]))
                groups += 1
            return {
                "coverage": safe_divide(coverage, groups),
                "shortage": shortage,
                "skill_shortage": skill_shortage,
            }

        current = self._all_metrics()
        return {
            "coverage": float(current["coverage"]),
            "shortage": float(current["shortage"]),
            "skill_shortage": float(current["skill_shortage"]),
        }

    def _reward(self, before, after, changed, valid):
        # Hospital-wide movement remains useful, but event-local improvement
        # gets a stronger signal so PPO learns the actual decision-support task.
        before_event = self._event_focus_metrics()
        # _event_focus_metrics must be evaluated after the action as well, so
        # reconstruct the before-event values from the pre-action global state
        # when the event has a single target.
        surge = list(self.last_event.get("demand_surge", [])) if self.last_event else []

        if surge:
            before_event = {"coverage": 0.0, "shortage": 0.0, "skill_shortage": 0.0}
            groups = 0
            for item in surge:
                unit = str(item.get("unit", ""))
                shift = normalize_shift(str(item.get("shift", "Day")))
                # The action has already been applied, so use the current state
                # and reverse the selected move locally where possible. A more
                # robust exact before/after calculation is supplied by the
                # outer V4.1 step override below.
                m = self._group_metrics(pd.Timestamp(self.current_date), unit, shift)
                before_event["shortage"] += float(m["shortage"])
                before_event["skill_shortage"] += float(m["skill_shortage"])
                before_event["coverage"] += float(safe_divide(m["assigned"], m["required"]))
                groups += 1
            before_event["coverage"] = safe_divide(before_event["coverage"], groups)
        # Fallback; exact event-local reward is calculated by step().
        reward = 0.0
        reward += 10.0 * (after["coverage"] - before["coverage"])
        reward += 12.0 * (after["skill_coverage"] - before["skill_coverage"])
        reward -= 2.0 * (after["shortage"] - before["shortage"])
        reward -= 3.0 * (after["skill_shortage"] - before["skill_shortage"])
        reward -= 4.0 * max(0.0, after["workload_gini"] - before["workload_gini"])
        reward -= 3.0 * max(0.0, after["overtime"] - before["overtime"])
        reward -= 2.0 * max(0.0, before["preference_score"] - after["preference_score"])
        if changed:
            reward -= 0.25
        if not valid:
            reward -= 2.0
        return float(reward)

    def step(self, action_index: int):
        if self.done:
            raise RuntimeError("Episode is already done. Call reset().")

        # Capture the event-local state BEFORE applying the action.
        event_before = self._event_focus_metrics()
        before = self._all_metrics()
        self.candidates = self.get_valid_actions()
        valid_index = 0 <= int(action_index) < len(self.candidates)
        action = self.candidates[int(action_index)] if valid_index else {"type": "invalid"}
        changed = False
        valid = valid_index
        if valid_index:
            changed = action.get("type") == "reassign"
            valid = self._apply_action(action)
        after = self._all_metrics()
        event_after = self._event_focus_metrics()

        reward = 0.0
        # Strong immediate signal for resolving the affected event.
        reward += 8.0 * (event_before["coverage"] - event_after["coverage"]) * -1.0
        reward += 4.0 * (event_before["shortage"] - event_after["shortage"])
        reward += 5.0 * (event_before["skill_shortage"] - event_after["skill_shortage"])
        # Preserve hospital-wide objectives.
        reward += 4.0 * (after["coverage"] - before["coverage"])
        reward += 5.0 * (after["skill_coverage"] - before["skill_coverage"])
        reward -= 1.5 * (after["shortage"] - before["shortage"])
        reward -= 2.0 * (after["skill_shortage"] - before["skill_shortage"])
        reward -= 4.0 * max(0.0, after["workload_gini"] - before["workload_gini"])
        reward -= 3.0 * max(0.0, after["overtime"] - before["overtime"])
        reward -= 2.0 * max(0.0, before["preference_score"] - after["preference_score"])
        if changed:
            reward -= 0.25
        if not valid:
            reward -= 2.0

        # Bonus for completely resolving the affected shortage.
        if event_before["shortage"] > 0 and event_after["shortage"] == 0:
            reward += 8.0
        if event_before["skill_shortage"] > 0 and event_after["skill_shortage"] == 0:
            reward += 10.0

        self.last_action = action
        action_date = pd.Timestamp(self.current_date)
        action_event = dict(self.last_event)

        self.current_index += 1
        if self.current_index >= len(self.episode_dates):
            self.done = True
            next_state = self.get_state()
        else:
            self.current_date = self.episode_dates[self.current_index]
            self.current_shift = "Day"
            self.last_event = self._inject_event_for_current_date()
            self._remove_absent_assignments()
            self.candidates = self.get_valid_actions()
            next_state = self.get_state()

        info = {
            "date": normalize_date(action_date),
            "action": action,
            "valid_action": bool(valid),
            "changed": bool(changed),
            "before": before,
            "after": after,
            "event": action_event,
            "event_before": event_before,
            "event_after": event_after,
            "event_shortage_reduction": float(event_before["shortage"] - event_after["shortage"]),
            "event_skill_shortage_reduction": float(event_before["skill_shortage"] - event_after["skill_shortage"]),
            "candidate_count": len(self.candidates),
        }
        return next_state, float(reward), self.done, info


class ActorCritic(nn.Module):
    def __init__(self, state_dim: int, action_dim: int, hidden_size: int = 128):
        super().__init__()
        self.shared = nn.Sequential(
            nn.Linear(state_dim, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
        )
        self.policy_head = nn.Linear(hidden_size, action_dim)
        self.value_head = nn.Linear(hidden_size, 1)

    def forward(self, x: torch.Tensor):
        h = self.shared(x)
        return self.policy_head(h), self.value_head(h).squeeze(-1)


class PPOAgent:
    def __init__(self, state_dim: int, action_dim: int, config: V4PPOConfig):
        self.config = config
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = ActorCritic(state_dim, action_dim, config.hidden_size).to(self.device)
        self.optimizer = optim.Adam(self.model.parameters(), lr=config.learning_rate)

    def _masked_dist(self, logits: torch.Tensor, mask: torch.Tensor):
        # Numerical guard: PPO can become unstable when an update produces
        # non-finite logits. Keep the policy distribution valid without
        # changing the action-mask semantics.
        logits = torch.nan_to_num(logits, nan=0.0, posinf=20.0, neginf=-20.0)
        safe_mask = mask.clone()
        no_valid = ~safe_mask.any(dim=-1)
        if no_valid.any():
            safe_mask[no_valid, 0] = True
        masked = logits.masked_fill(~safe_mask, -1e9)
        return Categorical(logits=masked)

    @torch.no_grad()
    def act(self, state: np.ndarray, valid_count: int, deterministic: bool = False):
        x = torch.as_tensor(state, dtype=torch.float32, device=self.device).unsqueeze(0)
        logits, value = self.model(x)
        mask = torch.zeros_like(logits, dtype=torch.bool)
        mask[:, :max(1, min(valid_count, logits.shape[1]))] = True
        dist = self._masked_dist(logits, mask)
        action = torch.argmax(dist.probs, dim=-1) if deterministic else dist.sample()
        log_prob = dist.log_prob(action)
        return int(action.item()), float(log_prob.item()), float(value.item())

    def evaluate_actions(self, states, actions, masks):
        logits, values = self.model(states)
        logits = torch.nan_to_num(logits, nan=0.0, posinf=20.0, neginf=-20.0)
        values = torch.nan_to_num(values, nan=0.0, posinf=1e4, neginf=-1e4)
        safe_masks = masks.clone()
        no_valid = ~safe_masks.any(dim=-1)
        if no_valid.any():
            safe_masks[no_valid, 0] = True
        masked = logits.masked_fill(~safe_masks, -1e9)
        dist = Categorical(logits=masked)
        return dist.log_prob(actions), dist.entropy(), values

    def update(self, batch: Dict[str, np.ndarray]):
        device = self.device
        states = torch.as_tensor(batch["states"], dtype=torch.float32, device=device)
        actions = torch.as_tensor(batch["actions"], dtype=torch.long, device=device)
        old_log_probs = torch.as_tensor(batch["log_probs"], dtype=torch.float32, device=device)
        returns = torch.as_tensor(batch["returns"], dtype=torch.float32, device=device)
        advantages = torch.as_tensor(batch["advantages"], dtype=torch.float32, device=device)
        masks = torch.as_tensor(batch["masks"], dtype=torch.bool, device=device)
        # std(unbiased=False) is important for one-transition episodes;
        # the default unbiased estimator is NaN when there is only one value.
        advantages = torch.nan_to_num(advantages, nan=0.0, posinf=1e4, neginf=-1e4)
        adv_std = advantages.std(unbiased=False)
        advantages = (advantages - advantages.mean()) / torch.clamp(adv_std, min=1e-8)
        returns = torch.nan_to_num(returns, nan=0.0, posinf=1e4, neginf=-1e4)
        old_log_probs = torch.nan_to_num(old_log_probs, nan=0.0, posinf=0.0, neginf=0.0)

        n = len(states)
        indices = np.arange(n)
        losses = []
        for _ in range(self.config.update_epochs):
            np.random.shuffle(indices)
            for start in range(0, n, self.config.minibatch_size):
                idx = indices[start:start + self.config.minibatch_size]
                mb = torch.as_tensor(idx, dtype=torch.long, device=device)
                new_lp, entropy, values = self.evaluate_actions(
                    states[mb], actions[mb], masks[mb]
                )
                ratio = torch.exp(new_lp - old_log_probs[mb])
                surr1 = ratio * advantages[mb]
                surr2 = torch.clamp(
                    ratio,
                    1.0 - self.config.clip_epsilon,
                    1.0 + self.config.clip_epsilon,
                ) * advantages[mb]
                policy_loss = -torch.min(surr1, surr2).mean()
                value_loss = nn.functional.smooth_l1_loss(values, returns[mb])
                entropy_bonus = entropy.mean()
                loss = policy_loss + self.config.value_coef * value_loss - self.config.entropy_coef * entropy_bonus
                if not torch.isfinite(loss):
                    self.optimizer.zero_grad()
                    continue

                self.optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.model.parameters(), self.config.max_grad_norm)
                self.optimizer.step()
                # Final guard against a rare non-finite optimizer update.
                with torch.no_grad():
                    for param in self.model.parameters():
                        param.data.copy_(torch.nan_to_num(param.data, nan=0.0, posinf=5.0, neginf=-5.0))
                losses.append(float(loss.item()))
        return float(np.mean(losses)) if losses else 0.0

    def save(self, path: str):
        torch.save({"model": self.model.state_dict(), "config": asdict(self.config)}, path)


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_env(data, roster, config: V4PPOConfig, seed: int):
    return EventAwareHospitalWorkforceEnvironment(
        data,
        roster,
        V3EnvironmentConfig(
            seed=seed,
            episode_days=config.episode_days,
            max_candidates=config.max_candidates,
        ),
    )


def collect_episode(env, agent: PPOAgent, start_date: Optional[str] = None):
    state = env.reset(start_date=start_date)
    states, actions, log_probs, values, rewards, dones, masks = [], [], [], [], [], [], []
    total_reward = 0.0
    steps = 0
    while not env.done:
        valid_count = min(len(env.candidates), agent.model.policy_head.out_features)
        action, lp, value = agent.act(state, valid_count, deterministic=False)
        action_mask = np.zeros(agent.model.policy_head.out_features, dtype=bool)
        action_mask[:valid_count] = True
        next_state, reward, done, _ = env.step(action)

        states.append(state)
        actions.append(action)
        log_probs.append(lp)
        values.append(value)
        rewards.append(float(reward))
        dones.append(bool(done))
        masks.append(action_mask)
        total_reward += reward
        steps += 1
        state = next_state

    # Bootstrap with zero because the episode ends after the final transition.
    advantages = np.zeros(steps, dtype=np.float32)
    returns = np.zeros(steps, dtype=np.float32)
    gae = 0.0
    next_value = 0.0
    for t in reversed(range(steps)):
        nonterminal = 0.0 if dones[t] else 1.0
        delta = rewards[t] + env.config.seed * 0.0 + 0.0 * next_value - values[t]
        # For an episodic terminal rollout, next_value is zero at the end.
        if t < steps - 1:
            delta = rewards[t] + agent.config.gamma * values[t + 1] - values[t]
        gae = delta + agent.config.gamma * agent.config.gae_lambda * nonterminal * gae
        advantages[t] = gae
        returns[t] = advantages[t] + values[t]

    batch = {
        "states": np.asarray(states, dtype=np.float32),
        "actions": np.asarray(actions, dtype=np.int64),
        "log_probs": np.asarray(log_probs, dtype=np.float32),
        "returns": returns,
        "advantages": advantages,
        "masks": np.asarray(masks, dtype=bool),
    }
    return batch, total_reward, steps


def train_agent(data, roster, config: V4PPOConfig):
    set_seed(config.seed)
    probe_env = make_env(data, roster, config, config.seed)
    probe_state = probe_env.reset()
    state_dim = int(len(probe_state))
    action_dim = int(config.max_candidates + 1)
    agent = PPOAgent(state_dim, action_dim, config)

    history = []
    for episode in range(1, config.episodes + 1):
        # Cycle through different valid demand dates so the policy does not
        # learn only one fixed week.
        demand_dates = sorted(pd.to_datetime(data["demand_shift"]["date"].unique()))
        start = demand_dates[(episode - 1) % max(1, len(demand_dates))]
        batch, episode_reward, steps = collect_episode(
            make_env(data, roster, config, config.seed + episode),
            agent,
            start_date=str(pd.Timestamp(start).date()),
        )
        loss = agent.update(batch)
        history.append({
            "episode": episode,
            "reward": float(episode_reward),
            "steps": int(steps),
            "loss": float(loss),
            "mean_advantage": float(batch["advantages"].mean()),
        })
        if episode == 1 or episode % 10 == 0:
            logger.info(
                "V4 PPO episode %d/%d | reward=%.3f | loss=%.5f",
                episode, config.episodes, episode_reward, loss,
            )

    return agent, history, state_dim, action_dim


def build_forced_scenario(data, start_date: pd.Timestamp):
    demand = data["demand_shift"].copy()
    demand["date"] = pd.to_datetime(demand["date"])
    rows = demand[demand["date"] == pd.Timestamp(start_date)]
    if rows.empty:
        raise ValueError(f"No demand rows for {start_date.date()}")
    target = rows.sort_values("required_staff", ascending=False).iloc[0]
    return {
        "date": str(pd.Timestamp(start_date).date()),
        "demand_surge": [{
            "unit": str(target["unit"]),
            "shift": str(target["shift"]),
            "extra_staff": 2,
        }],
    }, str(target["unit"]), str(target["shift"])


def evaluate_policy(data, roster, agent: PPOAgent, config: V4PPOConfig, episodes: int = 20):
    dates = sorted(pd.to_datetime(data["demand_shift"]["date"].unique()))
    records = []
    transitions = []
    for i in range(episodes):
        start = pd.Timestamp(dates[i % len(dates)])
        env = make_env(data, roster, config, config.seed + 10000 + i)
        forced, target_unit, target_shift = build_forced_scenario(data, start)

        # Select two baseline-assigned staff to make the absence scenario
        # reproducible while preserving exactly the same events for PPO and
        # the no-op baseline. Empty forced events on the remaining episode
        # dates disable V3's random event generator during evaluation.
        day_staff = roster[pd.to_datetime(roster["date"]) == start]["staff_id"].astype(str).unique().tolist()
        forced["absent_staff"] = day_staff[: min(2, len(day_staff))]
        episode_dates = sorted(pd.to_datetime(data["demand_shift"]["date"].unique()))
        episode_dates = [d for d in episode_dates if d >= start][:config.episode_days]
        forced_events = [forced]
        for d in episode_dates[1:]:
            forced_events.append({
                "date": str(pd.Timestamp(d).date()),
                "demand_surge": [],
                "absent_staff": [],
            })

        ppo_state = env.reset(start_date=str(start.date()), forced_events=forced_events)
        initial_metrics = env._all_metrics()
        ppo_total = 0.0
        ppo_actions = []
        ppo_event_shortage_reduction = 0.0
        ppo_event_skill_reduction = 0.0
        ppo_event_shortage_resolved = False
        ppo_event_skill_resolved = False
        while not env.done:
            valid_count = min(len(env.candidates), agent.model.policy_head.out_features)
            action, _, _ = agent.act(ppo_state, valid_count, deterministic=True)
            ppo_state, reward, done, info = env.step(action)
            ppo_total += reward
            ppo_actions.append(info["action"])
            ppo_event_shortage_reduction += info["event_shortage_reduction"]
            ppo_event_skill_reduction += info["event_skill_shortage_reduction"]
            if info["event_before"]["shortage"] > 0 and info["event_after"]["shortage"] == 0:
                ppo_event_shortage_resolved = True
            if info["event_before"]["skill_shortage"] > 0 and info["event_after"]["skill_shortage"] == 0:
                ppo_event_skill_resolved = True

        ppo_final = env._all_metrics()

        # Paired no-op baseline: same forced events, no adaptation.
        base_env = make_env(data, roster, config, config.seed + 10000 + i)
        base_state = base_env.reset(start_date=str(start.date()), forced_events=forced_events)
        base_initial = base_env._all_metrics()
        base_total = 0.0
        baseline_event_shortage_reduction = 0.0
        baseline_event_skill_reduction = 0.0
        while not base_env.done:
            base_state, reward, done, info = base_env.step(0)
            base_total += reward
            baseline_event_shortage_reduction += info["event_shortage_reduction"]
            baseline_event_skill_reduction += info["event_skill_shortage_reduction"]
        base_final = base_env._all_metrics()

        records.append({
            "episode": i + 1,
            "start_date": str(start.date()),
            "target_unit": target_unit,
            "target_shift": target_shift,
            "initial_coverage": initial_metrics["coverage"],
            "ppo_final_coverage": ppo_final["coverage"],
            "baseline_final_coverage": base_final["coverage"],
            "ppo_final_shortage": ppo_final["shortage"],
            "baseline_final_shortage": base_final["shortage"],
            "ppo_final_skill_shortage": ppo_final["skill_shortage"],
            "baseline_final_skill_shortage": base_final["skill_shortage"],
            "ppo_workload_gini": ppo_final["workload_gini"],
            "baseline_workload_gini": base_final["workload_gini"],
            "ppo_total_reward": ppo_total,
            "baseline_total_reward": base_total,
            "ppo_reassignments": sum(a.get("type") == "reassign" for a in ppo_actions),
            "ppo_event_shortage_reduction": ppo_event_shortage_reduction,
            "baseline_event_shortage_reduction": baseline_event_shortage_reduction,
            "ppo_event_skill_shortage_reduction": ppo_event_skill_reduction,
            "baseline_event_skill_shortage_reduction": baseline_event_skill_reduction,
            "ppo_event_shortage_resolved": int(ppo_event_shortage_resolved),
            "ppo_event_skill_shortage_resolved": int(ppo_event_skill_resolved),
        })
        transitions.append({
            "episode": i + 1,
            "start_date": str(start.date()),
            "forced_event": forced,
            "ppo_actions": ppo_actions,
        })
    return records, transitions


def run_v4(
    dataset_path: str,
    roster_path: Optional[str] = None,
    output_dir: str = "v4_outputs",
    episodes: int = 150,
    eval_episodes: int = 20,
    time_limit: int = 120,
):
    os.makedirs(output_dir, exist_ok=True)
    config = V4PPOConfig(
        episodes=episodes,
        output_dir=output_dir,
        time_limit=time_limit,
        learning_rate=1e-4,
        entropy_coef=0.005,
        update_epochs=6,
    )
    data, roster = load_v2_baseline(dataset_path, roster_path, time_limit)

    agent, history, state_dim, action_dim = train_agent(data, roster, config)
    model_path = os.path.join(output_dir, "v4_ppo_model.pt")
    agent.save(model_path)

    history_path = os.path.join(output_dir, "v4_training_history.json")
    with open(history_path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2)

    evaluation, transitions = evaluate_policy(data, roster, agent, config, eval_episodes)
    eval_path = os.path.join(output_dir, "v4_evaluation.csv")
    pd.DataFrame(evaluation).to_csv(eval_path, index=False)

    transitions_path = os.path.join(output_dir, "v4_evaluation_transitions.json")
    with open(transitions_path, "w", encoding="utf-8") as f:
        json.dump(transitions, f, indent=2)

    df = pd.DataFrame(evaluation)
    # Event-level improvement is the primary V4.1 diagnostic.
    summary = {
        "version": "4.1",
        "description": "Event-aware PPO training and paired dynamic evaluation on the V3 environment",
        "state_dim": state_dim,
        "action_dim": action_dim,
        "training_episodes": episodes,
        "evaluation_episodes": eval_episodes,
        "device": str(agent.device),
        "mean_ppo_coverage": float(df["ppo_final_coverage"].mean()),
        "mean_noop_coverage": float(df["baseline_final_coverage"].mean()),
        "mean_ppo_shortage": float(df["ppo_final_shortage"].mean()),
        "mean_noop_shortage": float(df["baseline_final_shortage"].mean()),
        "mean_ppo_skill_shortage": float(df["ppo_final_skill_shortage"].mean()),
        "mean_noop_skill_shortage": float(df["baseline_final_skill_shortage"].mean()),
        "mean_ppo_workload_gini": float(df["ppo_workload_gini"].mean()),
        "mean_noop_workload_gini": float(df["baseline_workload_gini"].mean()),
        "mean_ppo_reassignments": float(df["ppo_reassignments"].mean()),
        "mean_ppo_event_shortage_reduction": float(df["ppo_event_shortage_reduction"].mean()),
        "mean_baseline_event_shortage_reduction": float(df["baseline_event_shortage_reduction"].mean()),
        "mean_ppo_event_skill_shortage_reduction": float(df["ppo_event_skill_shortage_reduction"].mean()),
        "mean_baseline_event_skill_shortage_reduction": float(df["baseline_event_skill_shortage_reduction"].mean()),
        "event_shortage_resolution_rate": float(df["ppo_event_shortage_resolved"].mean()),
        "event_skill_shortage_resolution_rate": float(df["ppo_event_skill_shortage_resolved"].mean()),
    }
    summary_path = os.path.join(output_dir, "v4_evaluation_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    logger.info("V4 completed. Summary: %s", summary)
    return {
        "model": model_path,
        "training_history": history_path,
        "evaluation": eval_path,
        "evaluation_transitions": transitions_path,
        "evaluation_summary": summary_path,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train/evaluate Version 4 PPO hospital workforce agent.")
    parser.add_argument("--dataset", required=True, help="Path to hospital_hrm_dataset.xlsx")
    parser.add_argument("--roster", default=None, help="Optional V2 baseline roster CSV")
    parser.add_argument("--output", default="v4_outputs")
    parser.add_argument("--episodes", type=int, default=150)
    parser.add_argument("--eval-episodes", type=int, default=20)
    parser.add_argument("--time-limit", type=int, default=120)
    args = parser.parse_args()

    outputs = run_v4(
        dataset_path=args.dataset,
        roster_path=args.roster,
        output_dir=args.output,
        episodes=args.episodes,
        eval_episodes=args.eval_episodes,
        time_limit=args.time_limit,
    )
    print("\nVersion 4 outputs:")
    for key, path in outputs.items():
        print(f"- {key}: {path}")
